### ISSUE TITLE
Add the remaining focal and local functions that are supported in GeoTrellis

### ISSUE THREAD

**Issue by caseypt** [azavea/modellab-geoprocessing#18]
Implement endpoints for anything shown here that's not already implemented and is available in GeoTrellis:

<img width="602" alt="screen shot 2015-11-10 at 4 30 02 pm" src="https://cloud.githubusercontent.com/assets/1042475/11076359/505536ec-87c8-11e5-8e00-1d11852d0569.png">

<img width="595" alt="screen shot 2015-11-10 at 4 30 17 pm" src="https://cloud.githubusercontent.com/assets/1042475/11076365/59523196-87c8-11e5-818d-450b63f75ad2.png">

**Comment by jamesmcclain** [comment]
Should have a "+" symbol, but that seems not to be available in this repository.

**Comment by rajadain** [comment]
New labels can be created here: https://github.com/azavea/modellab-geoprocessing/labels

I added the `+` label and assigned it to this card.

**Comment by jamesmcclain** [comment]
Thanks
