### ISSUE TITLE
Double Breaks

### ISSUE THREAD

**Issue by echeipesh** [azavea/modellab-geoprocessing#28]
ModelLab needs the ability to define color breaks on double values, like NDVI which ranges between -1 and 1. This feature is enabled by PR: https://github.com/geotrellis/geotrellis/pull/1207

Also once above PR is merged ML dependency on GT needs to be incremented.

In short the breaks endpoint needs to accept breaks that are usable for both int and double layers. I would expect that they can share the format with extra parsing logic.

**Comment by echeipesh** [comment]
Also consider this comment from @caseypt:

"Within the context of ModelLab, when creating color breaks, is it possible to specify a color for no data?     Something like `null:#000000;`. Here’s the break format @eugene came up with: https://github.com/azavea/modellab-geoprocessing/blob/develop/sample/breaks/tr.data"

**Comment by caseypt** [comment]
Implemented in #30.
