### ISSUE TITLE
Include sample JSON files as part of JAR

### ISSUE THREAD

**Issue by hectcastro** [azavea/modellab-geoprocessing#6]
When the assembly JAR is created, it should include the JSON files within the top level `sample` directory.

**Comment by jamesmcclain** [comment]
Unless someone already knows how to do this, this could be harder the 1 point.  I think that you have to (a) figure out how to get SBT to package up the resources correctly then (b) access the resources from Scala.  The second point should not be that hard, but without documentation, prior experience, or luck, the first part could take a while.

**Comment by echeipesh** [comment]
You can put it in resources directory. Proj4 project in GT does this

**Comment by jamesmcclain** [comment]
Thank you
